apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-flask-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-flask
  template:
    metadata:
      labels:
        app: api-flask
    spec:
      containers:
      - name: flask-container
        image: mon-api-flask:latest
        ports:
        - containerPort: 5000
        securityContext:
         runAsNonRoot: true
        runAsUser: 1000