name: Pipeline CI-CD Securisee

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Lint Kubernetes YAML
        uses: stardog-union/kube-linter-action@v1
        with:
          directory: .

      - name: Lint Dockerfile
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile

      - name: Build Docker Image
        run: |
          docker build -t mon-api-flask:${{ github.sha }} .

      - name: Run Trivy FS scan (SCA)
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '.'
          format: 'table'
          severity: 'CRITICAL,HIGH'

      - name: Run Trivy Image scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'mon-api-flask:${{ github.sha }}'
          format: 'table'
          severity: 'CRITICAL,HIGH'