name: DevSecOps Pipeline

on:
  push:
    branches: [ "main", "master" ]

jobs:
  build-and-scan:
    name: Build, Lint and Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: YAML Linting
        uses: ibiqlik/action-yamllint@v3
        with:
          file_or_dir: k8s-deployment.yml

      - name: Dockerfile Linting
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile

      - name: Docker Image Build
        run: docker build -t mon-api-flask:latest .

      - name: Trivy FS Scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '.'
          format: 'table'
          exit-code: '0'

      - name: Trivy Image Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'mon-api-flask:latest'
          format: 'table'
          exit-code: '1'
          severity: 'CRITICAL,HIGH'

      - name: Conftest
        if: always()
        run: docker run --rm -v ${{ github.workspace }}:/workspace -w /workspace openpolicyagent/conftest test k8s-deployment.yml -p policy/